[mongodb]
uri="mongodb://localhost:27017"
dbname="devops_db"
vmMonitorColumnName="vm_monitor"
serverMonitorColumnName="server_monitor"
logColumnName="app_log"
clickLogColumnName="click_log"
serverInfoColumnName="server_log"

[logger]
bind="127.0.0.1"
port=10900
maxSize=1024

[monitor]
interval=5
eth="eth0"
block="vda"

[server.deploy.port]
min=10000
max=65500

[server.deploy.image]
prefix="deploy_"
postfix=""
[server.deploy.server]
prefix="service_"
postfix=""
