[mongodb]
dbname = "devops_db"
uri = "mongodb://localhost:27017"

clickLogColumnName = "click_log"
logColumnName = "app_log"
serverMonitorColumnName = "server_monitor"
serverRpcStatisticsColumnName = "server_rpc"
vmMonitorColumnName = "vm_monitor"

clickLogTTL = 2635200 # 30days + 12hours
logTTL = 2635200 # 30days + 12hours
serverMonitorTTL = 1339200 # 15 days + 12hour
serverRpcStatisticsTTL = 2635200 # 30days + 12hours
vmMonitorTTL = 1339200 # 15days + 12hours 

[logger]
bind = "127.0.0.1"
maxSize = 1024
port = 10900

[monitor]
block = "vda"
eth = "eth0"
interval = 60

[deploy]
imagePostfix = ""
imagePrefix = "deploy_"
serverPostfix = ""
serverPrefix = "server_"
