[mongodb]
dbname = "devops_db"
uri = "mongodb://localhost:27017"

clickLogColumnName = "click_log"
logColumnName = "app_log"
serverInfoColumnName = "server_log"
serverMonitorColumnName = "server_monitor"
vmMonitorColumnName = "vm_monitor"

[logger]
bind = "127.0.0.1"
maxSize = 1024
port = 10900

[monitor]
bind = "127.0.0.1"
port = 10901

block = "vda"
eth = "eth0"
interval = 60

[deploy]
imagePostfix = ""
imagePrefix = "deploy_"
serverPostfix = ""
serverPrefix = "server_"
