const SVR_FLAG_TEST = 1
const SVR_FLAG_GRAY = 2

const SVR_STATUS_INIT = 1
const SVR_STATUS_STOP = 2
const SVR_STATUS_RUNNING = 3
const SVR_STATUS_CORE = 4
const SVR_STATUS_RESTART = 5
const SVR_STATUS_DESTROY = 6

module.exports = {
    SVR_FLAG_TEST, SVR_FLAG_GRAY, SVR_STATUS_INIT, SVR_STATUS_RUNNING, SVR_STATUS_CORE, SVR_STATUS_RESTART, SVR_STATUS_STOP, SVR_STATUS_DESTROY
}