const SVR_FLAG_TEST = 1
const SVR_FLAG_GRAY = 2

const SVR_STATUS_INIT = 1
const SVR_STATUS_STOPPING = 3
const SVR_STATUS_STOPPED = 4
const SVR_STATUS_STARTING = 5
const SVR_STATUS_RESTARTING = 6
const SVR_STATUS_RUNNING = 10
const SVR_STATUS_DESTROYING = 21
const SVR_STATUS_DESTROYED = 22
const SVR_STATUS_UNKNOWN = 100

const VM_FLAG_READY = 1

module.exports = {
    SVR_FLAG_TEST, SVR_FLAG_GRAY,
    SVR_STATUS_INIT, SVR_STATUS_STOPPING, SVR_STATUS_STOPPED, SVR_STATUS_STARTING,
    SVR_STATUS_RUNNING, SVR_STATUS_DESTROYING, SVR_STATUS_RESTARTING,
    SVR_STATUS_DESTROYED, SVR_STATUS_UNKNOWN,
    VM_FLAG_READY
}