[package]
name = "agent"
version = "0.1.0"
authors = ["kadds <itmyxyf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb="1.1"
tokio= {version="0.2", features=["full"]}
toml = "0.5"
serde = "1.0"
lazy_static = "1.4"
daemonize = "0.4"
clap = "2.33"
notify = "5.0.0-pre.3"